mlx:
  models:
    qwen3:
      model_name: "Qwen/Qwen3-4B-Instruct-2507"
    llama8b:
      model_name: "mlx-community/Meta-Llama-3.1-8B-Instruct-8bit"
llama:
  models:
    qwen25:
      model_name: "bartowski/Qwen2.5-14B-Instruct-GGUF"
      model_type: "*Q4_K_M.gguf"
    qwen3:
      model_name: "bartowski/Qwen_Qwen3-4B-Instruct-2507-GGUF"
      model_type: "*Q8_0.gguf"
    llama8b:
      model_name: "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF"
      model_type: "*Q8_0.gguf"
torch:
  models:
    qwen25:
      model_name: "/Users/cyunker/models/qwen2/Qwen2.5-14B-Instruct-Q4_K_M.gguf"
      model_base: "Qwen/Qwen2.5-14B-Instruct"
      #model_name: "bartowski/Qwen2.5-14B-Instruct-GGUF"
      #model_type: "*Q4_K_M.gguf"
    qwen3:
      model_name: "Qwen/Qwen3-4B-Instruct-2507"
    llama8b:
      model_name: "meta-llama/Llama-3.1-8B-Instruct"

max_tokens: 1000
temperature: 0.7
top_k: 40
top_p: 0.7
min_p: 0.05
ctx_window: 1024
gpu_layers: 2
